import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding production demonstration dataset (non-destructive)...');

  // 1. Process Areas
  const processAreas = [
    {
      id: 'demo-pa-10',
      areaCode: 'DEMO-10',
      name: 'Feedwater System',
      description: 'Main boiler feedwater storage, treatment, and pumping facility.',
    },
    {
      id: 'demo-pa-12',
      areaCode: 'DEMO-12',
      name: 'Cooling Water System',
      description: 'Closed-loop non-contact cooling water towers and pumps.',
    },
    {
      id: 'demo-pa-15',
      areaCode: 'DEMO-15',
      name: 'Process Water System',
      description: 'Demineralized water purification, storage, and utility loops.',
    },
  ];

  for (const pa of processAreas) {
    await prisma.processArea.upsert({
      where: { id: pa.id },
      update: { name: pa.name, description: pa.description, areaCode: pa.areaCode },
      create: pa,
    });
  }

  // 2. Control Loops
  const controlLoops = [
    {
      id: 'demo-loop-101',
      loopNumber: '101',
      loopTag: 'DEMO-PT-101',
      description: 'Boiler Header Pressure Control',
      pidReference: 'P&ID-101-REV-C',
      processAreaId: 'demo-pa-10',
    },
    {
      id: 'demo-loop-215',
      loopNumber: '215',
      loopTag: 'DEMO-FT-215',
      description: 'Cooling Water Return Flow Rate',
      pidReference: 'P&ID-102-REV-A',
      processAreaId: 'demo-pa-12',
    },
    {
      id: 'demo-loop-301',
      loopNumber: '301',
      loopTag: 'DEMO-LT-301',
      description: 'Demineralized Water Tank Level',
      pidReference: 'P&ID-105-REV-B',
      processAreaId: 'demo-pa-15',
    },
    {
      id: 'demo-loop-410',
      loopNumber: '410',
      loopTag: 'DEMO-TT-410',
      description: 'Heat Exchanger Outlet Temperature',
      pidReference: 'P&ID-108-REV-A',
      processAreaId: 'demo-pa-12',
    },
    {
      id: 'demo-loop-502',
      loopNumber: '502',
      loopTag: 'DEMO-AIT-502',
      description: 'Process Water Conductivity Analyzer',
      pidReference: 'P&ID-112-REV-D',
      processAreaId: 'demo-pa-15',
    },
  ];

  for (const cl of controlLoops) {
    await prisma.controlLoop.upsert({
      where: { id: cl.id },
      update: {
        loopNumber: cl.loopNumber,
        loopTag: cl.loopTag,
        description: cl.description,
        pidReference: cl.pidReference,
        processAreaId: cl.processAreaId,
      },
      create: cl,
    });
  }

  // 3. Reference Standards
  const now = new Date();
  const thirtyDaysFuture = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);
  const ninetyDaysPast = new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000);
  const oneYearPast = new Date(now.getTime() - 365 * 24 * 60 * 60 * 1000);
  const oneYearFuture = new Date(now.getTime() + 365 * 24 * 60 * 60 * 1000);

  const referenceStandards = [
    {
      id: 'demo-std-1',
      assetTag: 'DEMO-STD-001',
      equipmentType: 'Process Calibrator',
      manufacturer: 'Fluke',
      model: '754',
      serialNumber: 'SN-DEMO-FLK754',
      accuracyClass: '±0.01% FS',
      certificateNumber: 'NIST-2026-0891',
      lastCalibratedDate: oneYearPast,
      calibrationDueDate: oneYearFuture,
      status: 'ACTIVE' as const,
    },
    {
      id: 'demo-std-2',
      assetTag: 'DEMO-STD-002',
      equipmentType: 'Temperature Calibrator',
      manufacturer: 'Rosemount',
      model: '3144P',
      serialNumber: 'SN-DEMO-RSM314',
      accuracyClass: '±0.02% FS',
      certificateNumber: 'NIST-2026-1102',
      lastCalibratedDate: oneYearPast,
      calibrationDueDate: oneYearFuture,
      status: 'ACTIVE' as const,
    },
    {
      id: 'demo-std-3',
      assetTag: 'DEMO-STD-003',
      equipmentType: 'Pressure Calibrator',
      manufacturer: 'Druck',
      model: 'DPI 620',
      serialNumber: 'SN-DEMO-DRK620',
      accuracyClass: '±0.025% FS',
      certificateNumber: 'NIST-2026-3390',
      lastCalibratedDate: oneYearPast,
      calibrationDueDate: thirtyDaysFuture,
      status: 'DUE_SOON' as const,
    },
    {
      id: 'demo-std-4',
      assetTag: 'DEMO-STD-004',
      equipmentType: 'Digital Multimeter',
      manufacturer: 'Keysight',
      model: '34465A',
      serialNumber: 'SN-DEMO-KEYS65',
      accuracyClass: '±0.0035% Reading',
      certificateNumber: 'NIST-2025-9981',
      lastCalibratedDate: new Date(now.getTime() - 400 * 24 * 60 * 60 * 1000),
      calibrationDueDate: ninetyDaysPast,
      status: 'EXPIRED' as const,
    },
  ];

  for (const std of referenceStandards) {
    await prisma.referenceStandard.upsert({
      where: { id: std.id },
      update: {
        assetTag: std.assetTag,
        equipmentType: std.equipmentType,
        manufacturer: std.manufacturer,
        model: std.model,
        serialNumber: std.serialNumber,
        accuracyClass: std.accuracyClass,
        certificateNumber: std.certificateNumber,
        lastCalibratedDate: std.lastCalibratedDate,
        calibrationDueDate: std.calibrationDueDate,
        status: std.status,
      },
      create: std,
    });
  }

  // 4. Instruments
  const fifteenDaysPast = new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000);
  const fifteenDaysFuture = new Date(now.getTime() + 15 * 24 * 60 * 60 * 1000);
  const thirtyDaysPast = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);

  const instruments = [
    {
      id: 'demo-inst-101a',
      tagNumber: 'DEMO-PIT-101A',
      instrumentType: 'Pressure Transmitter',
      manufacturer: 'Rosemount',
      model: '3051S',
      rangeMin: 0,
      rangeMax: 300,
      engineeringUnits: 'PSI',
      signalType: '4-20mA HART',
      location: 'Boiler 1 Main Header',
      status: 'ACTIVE' as const,
      maxPermissibleError: 0.5,
      processAreaId: 'demo-pa-10',
      controlLoopId: 'demo-loop-101',
      calibrationIntervalMonths: 12,
      lastCalibrationDate: fifteenDaysPast,
      nextCalibrationDueDate: oneYearFuture,
    },
    {
      id: 'demo-inst-101b',
      tagNumber: 'DEMO-PIT-101B',
      instrumentType: 'Pressure Transmitter',
      manufacturer: 'Yokogawa',
      model: 'EJA110E',
      rangeMin: 0,
      rangeMax: 300,
      engineeringUnits: 'PSI',
      signalType: '4-20mA HART',
      location: 'Boiler 1 Auxiliary Line',
      status: 'CALIBRATION_DUE' as const,
      maxPermissibleError: 0.5,
      processAreaId: 'demo-pa-10',
      controlLoopId: 'demo-loop-101',
      calibrationIntervalMonths: 12,
      lastCalibrationDate: oneYearPast,
      nextCalibrationDueDate: fifteenDaysFuture,
    },
    {
      id: 'demo-inst-215a',
      tagNumber: 'DEMO-FIT-215A',
      instrumentType: 'Flow Transmitter',
      manufacturer: 'Endress+Hauser',
      model: 'Promag 50P',
      rangeMin: 0,
      rangeMax: 1500,
      engineeringUnits: 'GPM',
      signalType: '4-20mA HART',
      location: 'Cooling Tower Return Line 1',
      status: 'ACTIVE' as const,
      maxPermissibleError: 0.25,
      processAreaId: 'demo-pa-12',
      controlLoopId: 'demo-loop-215',
      calibrationIntervalMonths: 12,
      lastCalibrationDate: thirtyDaysPast,
      nextCalibrationDueDate: oneYearFuture,
    },
    {
      id: 'demo-inst-301a',
      tagNumber: 'DEMO-LIT-301A',
      instrumentType: 'Level Transmitter',
      manufacturer: 'Vega',
      model: 'Puls 64',
      rangeMin: 0,
      rangeMax: 20,
      engineeringUnits: 'FT',
      signalType: '4-20mA HART',
      location: 'Demin Tank Top Flange',
      status: 'OVERDUE' as const,
      maxPermissibleError: 0.5,
      processAreaId: 'demo-pa-15',
      controlLoopId: 'demo-loop-301',
      calibrationIntervalMonths: 12,
      lastCalibrationDate: new Date(now.getTime() - 390 * 24 * 60 * 60 * 1000),
      nextCalibrationDueDate: thirtyDaysPast,
    },
    {
      id: 'demo-inst-410a',
      tagNumber: 'DEMO-TIT-410A',
      instrumentType: 'Temperature Transmitter',
      manufacturer: 'Rosemount',
      model: '644',
      rangeMin: 32,
      rangeMax: 250,
      engineeringUnits: '°F',
      signalType: '4-20mA RTD',
      location: 'HX-102 Outlet Pipe',
      status: 'ACTIVE' as const,
      maxPermissibleError: 0.2,
      processAreaId: 'demo-pa-12',
      controlLoopId: 'demo-loop-410',
      calibrationIntervalMonths: 12,
      lastCalibrationDate: fifteenDaysPast,
      nextCalibrationDueDate: oneYearFuture,
    },
    {
      id: 'demo-inst-502a',
      tagNumber: 'DEMO-AIT-502A',
      instrumentType: 'Conductivity Analyzer',
      manufacturer: 'Mettler Toledo',
      model: 'M400',
      rangeMin: 0,
      rangeMax: 50,
      engineeringUnits: 'µS/cm',
      signalType: '4-20mA',
      location: 'Demin Header Sample Panel',
      status: 'INACTIVE' as const,
      maxPermissibleError: 1.0,
      processAreaId: 'demo-pa-15',
      controlLoopId: 'demo-loop-502',
      calibrationIntervalMonths: 6,
      lastCalibrationDate: ninetyDaysPast,
      nextCalibrationDueDate: thirtyDaysFuture,
    },
    {
      id: 'demo-inst-102',
      tagNumber: 'DEMO-PIT-102',
      instrumentType: 'Pressure Transmitter',
      manufacturer: 'ABB',
      model: '266DSH',
      rangeMin: 0,
      rangeMax: 150,
      engineeringUnits: 'PSI',
      signalType: '4-20mA HART',
      location: 'Feedwater Pump Discharge',
      status: 'ACTIVE' as const,
      maxPermissibleError: 0.5,
      processAreaId: 'demo-pa-10',
      controlLoopId: 'demo-loop-101',
      calibrationIntervalMonths: 12,
      lastCalibrationDate: fifteenDaysPast,
      nextCalibrationDueDate: oneYearFuture,
    },
    {
      id: 'demo-inst-216',
      tagNumber: 'DEMO-FIT-216',
      instrumentType: 'Flow Transmitter',
      manufacturer: 'Emerson',
      model: '8800D Vortex',
      rangeMin: 0,
      rangeMax: 800,
      engineeringUnits: 'GPM',
      signalType: '4-20mA HART',
      location: 'Chilled Water Supply Line',
      status: 'CALIBRATION_DUE' as const,
      maxPermissibleError: 0.5,
      processAreaId: 'demo-pa-12',
      controlLoopId: 'demo-loop-215',
      calibrationIntervalMonths: 12,
      lastCalibrationDate: oneYearPast,
      nextCalibrationDueDate: fifteenDaysFuture,
    },
    {
      id: 'demo-inst-302',
      tagNumber: 'DEMO-LIT-302',
      instrumentType: 'Level Transmitter',
      manufacturer: 'Krohne',
      model: 'Optiflex 1300',
      rangeMin: 0,
      rangeMax: 15,
      engineeringUnits: 'FT',
      signalType: '4-20mA Radar',
      location: 'Condensate Tank Sump',
      status: 'ACTIVE' as const,
      maxPermissibleError: 0.5,
      processAreaId: 'demo-pa-15',
      controlLoopId: 'demo-loop-301',
      calibrationIntervalMonths: 12,
      lastCalibrationDate: thirtyDaysPast,
      nextCalibrationDueDate: oneYearFuture,
    },
    {
      id: 'demo-inst-411',
      tagNumber: 'DEMO-TIT-411',
      instrumentType: 'Temperature Transmitter',
      manufacturer: 'WIKA',
      model: 'T32',
      rangeMin: 0,
      rangeMax: 200,
      engineeringUnits: '°C',
      signalType: '4-20mA RTD',
      location: 'Boiler Deaerator Inlet',
      status: 'OVERDUE' as const,
      maxPermissibleError: 0.3,
      processAreaId: 'demo-pa-10',
      controlLoopId: 'demo-loop-101',
      calibrationIntervalMonths: 12,
      lastCalibrationDate: new Date(now.getTime() - 410 * 24 * 60 * 60 * 1000),
      nextCalibrationDueDate: thirtyDaysPast,
    },
    {
      id: 'demo-inst-503',
      tagNumber: 'DEMO-AIT-503',
      instrumentType: 'pH Analyzer',
      manufacturer: 'Hach',
      model: 'sc200',
      rangeMin: 0,
      rangeMax: 14,
      engineeringUnits: 'pH',
      signalType: '4-20mA',
      location: 'Effluent Water Pit',
      status: 'ACTIVE' as const,
      maxPermissibleError: 0.1,
      processAreaId: 'demo-pa-15',
      controlLoopId: 'demo-loop-502',
      calibrationIntervalMonths: 6,
      lastCalibrationDate: fifteenDaysPast,
      nextCalibrationDueDate: oneYearFuture,
    },
    {
      id: 'demo-inst-103',
      tagNumber: 'DEMO-PIT-103',
      instrumentType: 'Differential Pressure Transmitter',
      manufacturer: 'Honeywell',
      model: 'STD800',
      rangeMin: 0,
      rangeMax: 100,
      engineeringUnits: 'IN_H2O',
      signalType: '4-20mA HART',
      location: 'Filter Differential Pressure Panel',
      status: 'ACTIVE' as const,
      maxPermissibleError: 0.2,
      processAreaId: 'demo-pa-10',
      controlLoopId: 'demo-loop-101',
      calibrationIntervalMonths: 12,
      lastCalibrationDate: thirtyDaysPast,
      nextCalibrationDueDate: oneYearFuture,
    },
  ];

  for (const inst of instruments) {
    await prisma.instrument.upsert({
      where: { id: inst.id },
      update: {
        tagNumber: inst.tagNumber,
        instrumentType: inst.instrumentType,
        manufacturer: inst.manufacturer,
        model: inst.model,
        rangeMin: inst.rangeMin,
        rangeMax: inst.rangeMax,
        engineeringUnits: inst.engineeringUnits,
        signalType: inst.signalType,
        location: inst.location,
        status: inst.status,
        maxPermissibleError: inst.maxPermissibleError,
        processAreaId: inst.processAreaId,
        controlLoopId: inst.controlLoopId,
        calibrationIntervalMonths: inst.calibrationIntervalMonths,
        lastCalibrationDate: inst.lastCalibrationDate,
        nextCalibrationDueDate: inst.nextCalibrationDueDate,
      },
      create: inst,
    });
  }

  // 5. Calibration Records & Test Points
  const calibrationRecordsData = [
    {
      id: 'demo-cal-101',
      instrumentId: 'demo-inst-101a',
      calibrationDate: fifteenDaysPast,
      technicianName: 'Demo Technician',
      asFound: 0.12,
      asLeft: 0.05,
      passFail: true,
      notes: 'Routine 5-point calibration completed successfully. As-found within ±0.5% tolerance.',
      status: 'APPROVED' as const,
      submittedAt: fifteenDaysPast,
      approvedAt: fifteenDaysPast,
    },
    {
      id: 'demo-cal-102',
      instrumentId: 'demo-inst-101b',
      calibrationDate: thirtyDaysPast,
      technicianName: 'Demo Technician',
      asFound: 0.85, // Failed as-found (> 0.5% MPE)
      asLeft: 0.18,  // Adjusted to passing as-left
      passFail: true,
      notes: 'As-found error exceeded 0.5% MPE at 75% test point due to span drift. Re-zeroed and re-spanned. As-left passes within specs.',
      status: 'APPROVED' as const,
      submittedAt: thirtyDaysPast,
      approvedAt: thirtyDaysPast,
    },
    {
      id: 'demo-cal-215',
      instrumentId: 'demo-inst-215a',
      calibrationDate: thirtyDaysPast,
      technicianName: 'Demo Technician',
      asFound: 0.08,
      asLeft: 0.08,
      passFail: true,
      notes: 'Magmeter calibration verified against reference standard DEMO-STD-001. All test points pass.',
      status: 'APPROVED' as const,
      submittedAt: thirtyDaysPast,
      approvedAt: thirtyDaysPast,
    },
    {
      id: 'demo-cal-301',
      instrumentId: 'demo-inst-301a',
      calibrationDate: ninetyDaysPast,
      technicianName: 'Demo Technician',
      asFound: 1.25,
      asLeft: 1.25,
      passFail: false,
      notes: 'Radar level sensor output noisy due to antenna scaling. Unit failed MPE at 100% level. Work order issued.',
      status: 'REJECTED' as const,
      submittedAt: ninetyDaysPast,
      rejectedAt: ninetyDaysPast,
    },
    {
      id: 'demo-cal-410',
      instrumentId: 'demo-inst-410a',
      calibrationDate: fifteenDaysPast,
      technicianName: 'Demo Technician',
      asFound: 0.05,
      asLeft: 0.05,
      passFail: true,
      notes: 'RTD sensor bath calibration. Excellent linearity across 32-250°F range.',
      status: 'APPROVED' as const,
      submittedAt: fifteenDaysPast,
      approvedAt: fifteenDaysPast,
    },
    {
      id: 'demo-cal-502',
      instrumentId: 'demo-inst-502a',
      calibrationDate: ninetyDaysPast,
      technicianName: 'Demo Technician',
      asFound: 0.2,
      asLeft: 0.2,
      passFail: true,
      notes: 'Conductivity cell dry/wet check using NIST reference standards.',
      status: 'APPROVED' as const,
      submittedAt: ninetyDaysPast,
      approvedAt: ninetyDaysPast,
    },
    {
      id: 'demo-cal-102b',
      instrumentId: 'demo-inst-102',
      calibrationDate: fifteenDaysPast,
      technicianName: 'Demo Technician',
      asFound: 0.1,
      asLeft: 0.1,
      passFail: true,
      notes: 'Discharge pressure transmitter verification. Passes all points.',
      status: 'APPROVED' as const,
      submittedAt: fifteenDaysPast,
      approvedAt: fifteenDaysPast,
    },
    {
      id: 'demo-cal-216',
      instrumentId: 'demo-inst-216',
      calibrationDate: oneYearPast,
      technicianName: 'Demo Technician',
      asFound: 0.15,
      asLeft: 0.15,
      passFail: true,
      notes: 'Vortex meter signal generator calibration.',
      status: 'APPROVED' as const,
      submittedAt: oneYearPast,
      approvedAt: oneYearPast,
    },
    {
      id: 'demo-cal-302',
      instrumentId: 'demo-inst-302',
      calibrationDate: thirtyDaysPast,
      technicianName: 'Demo Technician',
      asFound: 0.06,
      asLeft: 0.06,
      passFail: true,
      notes: 'Condensate level radar calibration. Zero and span aligned.',
      status: 'APPROVED' as const,
      submittedAt: thirtyDaysPast,
      approvedAt: thirtyDaysPast,
    },
    {
      id: 'demo-cal-411',
      instrumentId: 'demo-inst-411',
      calibrationDate: oneYearPast,
      technicianName: 'Demo Technician',
      asFound: 0.22,
      asLeft: 0.22,
      passFail: true,
      notes: 'Deaerator inlet RTD check.',
      status: 'APPROVED' as const,
      submittedAt: oneYearPast,
      approvedAt: oneYearPast,
    },
    {
      id: 'demo-cal-503',
      instrumentId: 'demo-inst-503',
      calibrationDate: fifteenDaysPast,
      technicianName: 'Demo Technician',
      asFound: 0.04,
      asLeft: 0.04,
      passFail: true,
      notes: 'Two-point pH buffer calibration (pH 4.01 and pH 7.00). Slope = 98.6%.',
      status: 'APPROVED' as const,
      submittedAt: fifteenDaysPast,
      approvedAt: fifteenDaysPast,
    },
    {
      id: 'demo-cal-103',
      instrumentId: 'demo-inst-103',
      calibrationDate: thirtyDaysPast,
      technicianName: 'Demo Technician',
      asFound: 0.09,
      asLeft: 0.09,
      passFail: true,
      notes: 'Differential pressure transmitter static line pressure check.',
      status: 'APPROVED' as const,
      submittedAt: thirtyDaysPast,
      approvedAt: thirtyDaysPast,
    },
    {
      id: 'demo-cal-pending1',
      instrumentId: 'demo-inst-101b',
      calibrationDate: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
      technicianName: 'technician.demo@caltrack.com',
      asFound: 0.11,
      asLeft: 0.11,
      passFail: true,
      notes: 'Calibration record submitted by technician for QA review.',
      status: 'PENDING_REVIEW' as const,
      submittedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
    },
    {
      id: 'demo-cal-draft1',
      instrumentId: 'demo-inst-216',
      calibrationDate: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000),
      technicianName: 'technician.demo@caltrack.com',
      asFound: 0.05,
      asLeft: 0.05,
      passFail: true,
      notes: 'In-progress draft calibration record.',
      status: 'DRAFT' as const,
    },
    {
      id: 'demo-cal-pending2',
      instrumentId: 'demo-inst-301a',
      calibrationDate: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
      technicianName: 'technician.demo@caltrack.com',
      asFound: 0.14,
      asLeft: 0.14,
      passFail: true,
      notes: 'Re-calibration following maintenance cleaning. Submitted for QA sign-off.',
      status: 'PENDING_REVIEW' as const,
      submittedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
    },
  ];

  for (const cal of calibrationRecordsData) {
    await prisma.calibrationRecord.upsert({
      where: { id: cal.id },
      update: {
        instrumentId: cal.instrumentId,
        calibrationDate: cal.calibrationDate,
        technicianName: cal.technicianName,
        asFound: cal.asFound,
        asLeft: cal.asLeft,
        passFail: cal.passFail,
        notes: cal.notes,
        status: cal.status,
        submittedAt: cal.submittedAt,
        approvedAt: cal.approvedAt,
        rejectedAt: cal.rejectedAt,
      },
      create: cal,
    });
  }

  // 6. Test Points for Calibration Records (5-point calibration: 0%, 25%, 50%, 75%, 100%)
  const testPoints = [
    // Points for demo-cal-101 (Range 0-300 PSI, 4-20mA)
    { id: 'demo-tp-101-1', calibrationRecordId: 'demo-cal-101', targetInput: 0, expectedOutput: 4.0, asFoundOutput: 4.01, asLeftOutput: 4.0, asFoundError: 0.06, asLeftError: 0.0, passFail: true },
    { id: 'demo-tp-101-2', calibrationRecordId: 'demo-cal-101', targetInput: 75, expectedOutput: 8.0, asFoundOutput: 8.02, asLeftOutput: 8.01, asFoundError: 0.12, asLeftError: 0.06, passFail: true },
    { id: 'demo-tp-101-3', calibrationRecordId: 'demo-cal-101', targetInput: 150, expectedOutput: 12.0, asFoundOutput: 12.01, asLeftOutput: 12.0, asFoundError: 0.06, asLeftError: 0.0, passFail: true },
    { id: 'demo-tp-101-4', calibrationRecordId: 'demo-cal-101', targetInput: 225, expectedOutput: 16.0, asFoundOutput: 16.03, asLeftOutput: 16.01, asFoundError: 0.19, asLeftError: 0.06, passFail: true },
    { id: 'demo-tp-101-5', calibrationRecordId: 'demo-cal-101', targetInput: 300, expectedOutput: 20.0, asFoundOutput: 20.02, asLeftOutput: 20.0, asFoundError: 0.12, asLeftError: 0.0, passFail: true },

    // Points for demo-cal-102 (Failed as-found -> corrected as-left)
    { id: 'demo-tp-102-1', calibrationRecordId: 'demo-cal-102', targetInput: 0, expectedOutput: 4.0, asFoundOutput: 4.15, asLeftOutput: 4.01, asFoundError: 0.94, asLeftError: 0.06, passFail: false },
    { id: 'demo-tp-102-2', calibrationRecordId: 'demo-cal-102', targetInput: 75, expectedOutput: 8.0, asFoundOutput: 8.12, asLeftOutput: 8.02, asFoundError: 0.75, asLeftError: 0.12, passFail: false },
    { id: 'demo-tp-102-3', calibrationRecordId: 'demo-cal-102', targetInput: 150, expectedOutput: 12.0, asFoundOutput: 12.14, asLeftOutput: 12.01, asFoundError: 0.88, asLeftError: 0.06, passFail: false },
    { id: 'demo-tp-102-4', calibrationRecordId: 'demo-cal-102', targetInput: 225, expectedOutput: 16.0, asFoundOutput: 16.11, asLeftOutput: 16.02, asFoundError: 0.69, asLeftError: 0.12, passFail: false },
    { id: 'demo-tp-102-5', calibrationRecordId: 'demo-cal-102', targetInput: 300, expectedOutput: 20.0, asFoundOutput: 20.10, asLeftOutput: 20.01, asFoundError: 0.63, asLeftError: 0.06, passFail: false },
  ];

  for (const tp of testPoints) {
    await prisma.calibrationTestPoint.upsert({
      where: { id: tp.id },
      update: {
        targetInput: tp.targetInput,
        expectedOutput: tp.expectedOutput,
        asFoundOutput: tp.asFoundOutput,
        asLeftOutput: tp.asLeftOutput,
        asFoundError: tp.asFoundError,
        asLeftError: tp.asLeftError,
        passFail: tp.passFail,
      },
      create: tp,
    });
  }

  // 7. Work Orders
  const workOrders = [
    {
      id: 'demo-wo-101',
      workOrderNumber: 'DEMO-WO-2026-001',
      instrumentId: 'demo-inst-101b',
      status: 'OPEN' as const,
      priority: 'HIGH' as const,
      assignedTechnician: 'technician.demo@caltrack.com',
      scheduledDate: fifteenDaysFuture,
      description: 'Annual calibration due for Boiler 1 auxiliary pressure transmitter DEMO-PIT-101B.',
    },
    {
      id: 'demo-wo-102',
      workOrderNumber: 'DEMO-WO-2026-002',
      instrumentId: 'demo-inst-301a',
      status: 'IN_PROGRESS' as const,
      priority: 'CRITICAL' as const,
      assignedTechnician: 'technician.demo@caltrack.com',
      scheduledDate: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
      description: 'Overdue level transmitter calibration and antenna cleaning for DEMO-LIT-301A.',
    },
    {
      id: 'demo-wo-103',
      workOrderNumber: 'DEMO-WO-2026-003',
      instrumentId: 'demo-inst-101a',
      status: 'COMPLETED' as const,
      priority: 'MEDIUM' as const,
      assignedTechnician: 'technician.demo@caltrack.com',
      scheduledDate: fifteenDaysPast,
      completedDate: fifteenDaysPast,
      description: 'Routine 5-point calibration for header pressure transmitter DEMO-PIT-101A.',
    },
  ];

  for (const wo of workOrders) {
    await prisma.workOrder.upsert({
      where: { id: wo.id },
      update: {
        workOrderNumber: wo.workOrderNumber,
        instrumentId: wo.instrumentId,
        status: wo.status,
        priority: wo.priority,
        assignedTechnician: wo.assignedTechnician,
        scheduledDate: wo.scheduledDate,
        completedDate: wo.completedDate,
        description: wo.description,
      },
      create: wo,
    });
  }

  // 8. Audit Events
  const auditEvents = [
    {
      id: 'demo-audit-1',
      entityType: 'Instrument',
      entityId: 'demo-inst-101a',
      action: 'CREATE',
      changedBy: 'admin.demo@caltrack.com',
      timestamp: new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000),
      reason: 'Initial plant instrumentation commission',
    },
    {
      id: 'demo-audit-2',
      entityType: 'CalibrationRecord',
      entityId: 'demo-cal-101',
      action: 'SUBMIT_CALIBRATION',
      changedBy: 'technician.demo@caltrack.com',
      timestamp: fifteenDaysPast,
      reason: 'Submitted routine 5-point calibration for review',
    },
    {
      id: 'demo-audit-3',
      entityType: 'CalibrationRecord',
      entityId: 'demo-cal-101',
      action: 'APPROVE_CALIBRATION',
      changedBy: 'qa.demo@caltrack.com',
      timestamp: fifteenDaysPast,
      reason: 'Verified test point tolerances. QA sign-off approved.',
    },
    {
      id: 'demo-audit-4',
      entityType: 'CalibrationRecord',
      entityId: 'demo-cal-301',
      action: 'REJECT_CALIBRATION',
      changedBy: 'qa.demo@caltrack.com',
      timestamp: ninetyDaysPast,
      reason: '100% test point exceeded MPE threshold. Work order required.',
    },
  ];

  for (const audit of auditEvents) {
    await prisma.auditEvent.upsert({
      where: { id: audit.id },
      update: {
        entityType: audit.entityType,
        entityId: audit.entityId,
        action: audit.action,
        changedBy: audit.changedBy,
        timestamp: audit.timestamp,
        reason: audit.reason,
      },
      create: audit,
    });
  }

  console.log('Production demonstration dataset successfully populated.');
}

main()
  .catch((err) => {
    console.error('Failed to seed demonstration dataset:', err.message);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
